### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by zw1765** [NagatoYuki0943/anomalib-openvino-cpp#5]
请问一下这个C++版的部署环境是Ubuntu下的吗

**Comment by zw1765** [comment]
我现在的是win10+vs2019 CMake不成功
![Uploading YZCL(E9@B$3)9]S~(H8`Q9O.png…]()

**Comment by zw1765** [comment]
> 我是在windows上运行的，Ubuntu应该也可以

我现在的是win10+vs2019 CMake会报一堆错误的

**Comment by zw1765** [comment]
> 我是在windows上运行的，Ubuntu应该也可以

![YZCL(E9@B$3)9 S~(H8`Q9O](https://github.com/NagatoYuki0943/anomalib-openvino-cpp/assets/86357595/99b47447-0010-4dc4-b556-c0ef46fa6287)

**Comment by NagatoYuki0943** [comment]
试试重新建一个项目，把我的代码复制进去再试试

**Comment by zw1765** [comment]
> 试试重新建一个项目，把我的代码复制进去再试试

你用的是什么版本的呀，vs、opencv、onnx这些

**Comment by NagatoYuki0943** [comment]
vs2022（这个感觉差别不大），opencv：4.9.0，onnx：1.17.0

**Comment by zw1765** [comment]
> vs2022（这个感觉差别不大），opencv：4.9.0，onnx：1.17.0

我感觉是环境没配置好。请问一下你这里的环境配置是在哪里配置的呀
![GC){NVIMH@Y(D2@{T@VYR66](https://github.com/NagatoYuki0943/anomalib-openvino-cpp/assets/86357595/7e6b7a8e-ff7e-4530-b13d-00c38d5fcd22)

**Comment by zw1765** [comment]
我配的环境
![C%N_% `$I T{KWA8`UEVYD](https://github.com/NagatoYuki0943/anomalib-openvino-cpp/assets/86357595/63e3dc89-c732-49e4-959d-302395b78841)

**Comment by NagatoYuki0943** [comment]
包含目录 类似下面
```
D:\ml\opencv\build\include
D:\ml\w_openvino_toolkit_windows\runtime\include
```
其他的我用的lib目录我放进了环境变量中，你也可以放进库目录

![31XV`D) PBT I_U3_J5RIE9](https://github.com/NagatoYuki0943/anomalib-openvino-cpp/assets/72508155/104af8f0-b9b3-4a2b-a1ea-80df21e564ef)

**Comment by zw1765** [comment]
> 包含目录 类似下面
> 
> ```
> D:\ml\opencv\build\include
> D:\ml\w_openvino_toolkit_windows\runtime\include
> ```
> 
> 其他的我用的lib目录我放进了环境变量中，你也可以放进库目录
> 
> ![31XV`D) PBT I_U3_J5RIE9](https://private-user-images.githubusercontent.com/72508155/317552113-104af8f0-b9b3-4a2b-a1ea-80df21e564ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTQ3MzMsIm5iZiI6MTcxMTU5NDQzMywicGF0aCI6Ii83MjUwODE1NS8zMTc1NTIxMTMtMTA0YWY4ZjAtYjliMy00YTJiLWExZWEtODBkZjIxZTU2NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyNTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NWY2MWE3N2UzMjcwNmE0NzIxNjliZTdlMDhjNGQzODc1NzM4NGRmYTU1MjFiZWY0NDJhOTNiNWNlMjI2YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bbg9W1yVT3H6cvFrRvG-o02LK7ba0Nenon3F9Hzhp10)

这个问题解决了，感谢你

**Comment by zw1765** [comment]
还有个问题，我想问一下就是openvino 格式的bin权重和偏置参数文件不需要输入吗。我看参数路径没有看到这个bin文件

**Comment by NagatoYuki0943** [comment]
正常情况下 xml 和 bin 是放在同一个文件夹中，openvino的文件就是读取xml文件，应该会找相同目录同名的bin文件

**Comment by zw1765** [comment]
好的，感谢。

> 正常情况下 xml 和 bin 是放在同一个文件夹中，openvino的文件就是读取xml文件，应该会找相同目录同名的bin文件

**Comment by HonestyBrave** [comment]
博主windows上openvino用的什么版本
